#!/bin/bash

#SBATCH --job-name=Output
#SBATCH --partition=west
#SBATCH --account=papenfuss
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=4
#SBATCH --output=timescript.out

srun ./timescript

echo "fertig" > job_script.out
